# Generated by Django 4.2.7 on 2024-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='titleImage',
            field=models.ImageField(null=True, upload_to='titleImage'),
        ),
    ]
