# Generated by Django 4.2.7 on 2024-01-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('dtCreated', models.DateTimeField(auto_now_add=True)),
                ('dtUpdated', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('episodeNumber', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('content', models.ImageField(upload_to='')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('releasedDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('content', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAuthor', models.BooleanField(default=False)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribingAuthors', to='webtoon.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('isFinished', models.BooleanField(default=False)),
                ('releasedDate', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedWebtoons', to='webtoon.userprofile')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribingWebtoons', to='webtoon.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='tag',
            name='webtoons',
            field=models.ManyToManyField(blank=True, related_name='tags', to='webtoon.webtoon'),
        ),
        migrations.AddField(
            model_name='episode',
            name='likedBy',
            field=models.ManyToManyField(blank=True, related_name='likedEpisodes', to='webtoon.userprofile'),
        ),
        migrations.AddField(
            model_name='episode',
            name='ratedBy',
            field=models.ManyToManyField(blank=True, related_name='ratedEpisodes', to='webtoon.userprofile'),
        ),
        migrations.AddField(
            model_name='episode',
            name='webtoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='webtoon.webtoon'),
        ),
        migrations.AddField(
            model_name='comment',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webtoon.userprofile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikedBy',
            field=models.ManyToManyField(blank=True, related_name='dislikedComments', to='webtoon.userprofile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likedBy',
            field=models.ManyToManyField(blank=True, related_name='likedComments', to='webtoon.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('webtoon', 'episodeNumber')},
        ),
    ]
