# Generated by Django 4.2.7 on 2024-01-14 14:10

from django.db import migrations, models
import webtoon.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='name',
            field=models.CharField(max_length=10, validators=[webtoon.validators.isDayName]),
        ),
    ]
