# Generated by Django 4.2.7 on 2024-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_alter_webtoon_titleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='uploadDays',
            field=models.ManyToManyField(blank=True, related_name='webtoons', to='webtoon.dayofweek'),
        ),
    ]
