# Generated by Django 4.2.7 on 2024-01-11 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webtoon', '0002_comment_dayofweek_episode_tag_userprofile_webtoon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikedBy',
            field=models.ManyToManyField(blank=True, related_name='dislikedComments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likedBy',
            field=models.ManyToManyField(blank=True, related_name='likedComments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='episode',
            name='likedBy',
            field=models.ManyToManyField(blank=True, related_name='likedEpisodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='episode',
            name='ratedBy',
            field=models.ManyToManyField(blank=True, related_name='ratedEpisodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedWebtoons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribingWebtoons', to=settings.AUTH_USER_MODEL),
        ),
    ]
