# Generated by Django 4.2.7 on 2024-02-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0004_alter_webtoon_titleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='titleImage',
            field=models.ImageField(default='titleImage/default', upload_to='titleImage/'),
        ),
    ]
