# Generated by Django 4.2.7 on 2024-01-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0005_alter_dayofweek_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='introduction',
            field=models.CharField(default='안녕하세요', max_length=200),
        ),
    ]
