# Generated by Django 4.2.7 on 2024-02-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0005_alter_webtoon_titleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='thumbnail',
            field=models.ImageField(default='thumbnail/default.jpg', upload_to='thumbnail/'),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='titleImage',
            field=models.ImageField(default='titleImage/default.jpg', upload_to='tileImage/'),
        ),
    ]
