# Generated by Django 4.2.7 on 2024-01-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0006_rename_rating_episode_totalrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='dislikedBy',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='likedBy',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislikedBy',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likedBy',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikedBy',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='likedBy',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
