# Generated by Django 4.2.7 on 2024-01-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0006_userprofile_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.CharField(max_length=200),
        ),
    ]
