# Generated by Django 4.2.7 on 2024-02-01 15:25

from django.db import migrations, models
import django.db.models.deletion
import webtoon.utils


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0007_episode_imagenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=webtoon.utils.image_upload_path)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='webtoon.episode')),
            ],
        ),
    ]
