# Generated by Django 4.2.7 on 2024-01-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0007_episode_dislikedby_episode_likedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislikedBy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likedBy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='episode',
            name='dislikedBy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='episode',
            name='likedBy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
