# Generated by Django 4.2.7 on 2024-02-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0007_episode_imagenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='releasedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
