# Generated by Django 4.2.7 on 2024-02-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0008_episodeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeimage',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webtoon.episode'),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='releasedDate',
            field=models.DateTimeField(),
        ),
    ]
