# Generated by Django 4.2.7 on 2024-02-02 12:31

from django.db import migrations, models
import django.db.models.deletion
import webtoon.utils


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0008_episodeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.ImageField(default='thumbnail/default.jpg', upload_to=webtoon.utils.thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='episodeimage',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webtoon.episode'),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='titleImage',
            field=models.ImageField(default='titleImage/default.jpg', upload_to=webtoon.utils.titleImage_upload_path),
        ),
    ]
