# Generated by Django 4.2.7 on 2024-01-29 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0010_remove_episode_dislikedby_webtoon_titleimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='titleImage',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
