# Generated by Django 4.2.7 on 2024-02-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0011_alter_episode_releaseddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='releasedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
