# Generated by Django 4.2.7 on 2024-02-02 12:36

from django.db import migrations, models
import webtoon.utils


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0012_alter_episode_releaseddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.ImageField(default='thumbnail/default.jpg', upload_to=webtoon.utils.thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='titleImage',
            field=models.ImageField(default='titleImage/default.jpg', upload_to=webtoon.utils.titleImage_upload_path),
        ),
    ]
