# Generated by Django 4.2.7 on 2024-02-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0014_alter_webtoon_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='imageNumber',
        ),
    ]
